codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
    target: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "include/timezone/.*"
  - "include/SuiteGraphs/.*"
  - "include/social/.*"
  - "include/Smarty/.*"
  - "include/reCaptcha/.*"
  - "include/phpmailer/.*"
  - "include/Pear/.*"
  - "include/pclzip/.*"
  - "include/nusoap/.*"
  - "include/HTTP_WebDAV_Server/.*"
  - "include/HTMLPurifier/.*"
  - "include/SugarXHprof/.*"
  - "include/ytree/.*"
  - "include/php-sql-parser.php"
  - "include/parsecsv.lib.php"
  - "modules/AOS_PDF_Templates/PDF_Lib/.*"
  - "Zend/.*"
  - "modules/AOD_Index/Lib/.*"
  - "modules/Users/authentication/SAML2Authenticate/lib/.*"
  - "install/demoData.en_us.php"
  - "include/tcpdf/.*"
  - "modules/AOR_Charts/lib/.*"